name: CI

on:
  workflow_dispatch:  # This allows manual triggering
  push:
    branches:
      - main  # Adjust this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here
